name: Generate terraform docs

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '*.tf'
      - 'modules/**/*.tf'
      - '.terraform-docs.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Render terraform docs
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"